export const ADD_CAMERA = "ADD_CAMERA";
export const ADD_CAMERA_TYPE = "ADD_CAMERA_TYPE";
export const DELETE_CAMERA_TYPE = "DELETE_CAMERA_TYPE";
export const DELETE_CAMERA = "DELETE_CAMERA";
export const EDIT_CAMERA_TYPE = "EDIT_CAMERA_TYPE"
export const EDIT_CAMERA = "EDIT_CAMERA"